/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#c6c6c7",
        "primary-fixed": "#e2e2e2",
        "primary-dim": "#b8b9b9",
        "tertiary-container": "#eceaf3",
        "on-tertiary-fixed-variant": "#626269",
        "secondary-container": "#3a3b42",
        "outline": "#75757c",
        "tertiary-fixed": "#efedf6",
        "secondary-dim": "#9d9da6",
        "surface-container-lowest": "#000000",
        "tertiary": "#fbf8ff",
        "error-container": "#7f2927",
        "surface": "#0e0e10",
        "on-surface-variant": "#acaab1",
        "on-surface": "#e7e4ec",
        "error-dim": "#bb5551",
        "outline-variant": "#47474e",
        "on-primary": "#3f4041",
        "on-secondary-fixed": "#3e3f46",
        "error": "#ee7d77",
        "surface-container-highest": "#25252b",
        "inverse-primary": "#5e5f60",
        "on-primary-fixed": "#3e4040",
        "on-error-container": "#ff9993",
        "surface-container-high": "#1f1f24",
        "surface-variant": "#25252b",
        "on-primary-container": "#d0d0d0",
        "on-secondary-container": "#bfbec8",
        "surface-container": "#19191d",
        "background": "#0e0e10",
        "secondary": "#9d9da6",
        "on-background": "#e7e4ec",
        "inverse-on-surface": "#565457",
        "on-tertiary": "#5f5e66",
        "surface-bright": "#2b2c32",
        "surface-container-low": "#131316",
        "inverse-surface": "#fcf8fb",
        "primary-container": "#454747",
        "surface-dim": "#0e0e10",
        "on-secondary": "#1e2027",
        "on-error": "#490106",
        "on-tertiary-container": "#56565d",
        "primary": "#c6c6c7",
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      },
    },
  },
  plugins: [],
}
